# Generated by Django 4.1.5 on 2023-01-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_food_enq_food_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_enq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('reason', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='food_request',
        ),
    ]
