# Generated by Django 4.1.5 on 2023-01-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_food_enq_delete_food_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='food_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('day', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=20)),
                ('reason', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='food_enq',
        ),
    ]
