# Generated by Django 4.1.5 on 2023-06-03 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_food_enquiry_delete_food_request'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='food_enquiry',
            new_name='Food_request',
        ),
    ]
