# Generated by Django 4.1.5 on 2023-06-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_rename_food_enquiry_food_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('admn', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=50)),
                ('relate', models.CharField(max_length=50)),
                ('rphone', models.CharField(max_length=50)),
                ('add', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
                ('rdate', models.CharField(max_length=50)),
                ('rtime', models.CharField(max_length=50)),
            ],
        ),
    ]
